apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v3.10.0
          ports:
            - containerPort: 5000
          command: ["mlflow", "server"]
          args:
            - "--backend-store-uri=sqlite:///mlflow.db"
            - "--default-artifact-root=mlflow-artifacts:/"
            - "--artifacts-destination=/mlflow/artifacts"
            - "--serve-artifacts"
            - "--host=0.0.0.0"
            - "--port=5000"
          volumeMounts:
            - name: mlflow-artifacts
              mountPath: /mlflow
      volumes:
        - name: mlflow-artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
